In [1]:
import os
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [2]:
os.getcwd()
os.chdir('/Users/anvifranta/downloads')

In [91]:
#importing dataset
bnb = pd.read_csv('airbnb_prices.csv')

In [17]:
bnb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74111 entries, 0 to 74110
Data columns (total 28 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   id                      74111 non-null  int64  
 1   log_price               74111 non-null  float64
 2   property_type           74111 non-null  object 
 3   room_type               74111 non-null  object 
 4   amenities               74111 non-null  object 
 5   accommodates            74111 non-null  int64  
 6   bathrooms               73911 non-null  float64
 7   bed_type                74111 non-null  object 
 8   cancellation_policy     74111 non-null  object 
 9   cleaning_fee            74111 non-null  bool   
 10  city                    74111 non-null  object 
 11  description             74111 non-null  object 
 12  first_review            58247 non-null  object 
 13  host_has_profile_pic    73923 non-null  object 
 14  host_identity_verified  73923 non-null

In [40]:
bnb.head()

id  log_price property_type        room_type  \
0   6901257   5.010635     Apartment  Entire home/apt   
1   6304928   5.129899     Apartment  Entire home/apt   
2   7919400   4.976734     Apartment  Entire home/apt   
3  13418779   6.620073         House  Entire home/apt   
4   3808709   4.744932     Apartment  Entire home/apt   

                                           amenities  accommodates  bathrooms  \
0  {"Wireless Internet","Air conditioning",Kitche...             3        1.0   
1  {"Wireless Internet","Air conditioning",Kitche...             7        1.0   
2  {TV,"Cable TV","Wireless Internet","Air condit...             5        1.0   
3  {TV,"Cable TV",Internet,"Wireless Internet",Ki...             4        1.0   
4  {TV,Internet,"Wireless Internet","Air conditio...             2        1.0   

   bed_type cancellation_policy  cleaning_fee  ... last_review   latitude  \
0  Real Bed              strict          True  ...  18/07/2016  40.696524   
1  Real Bed              strict          True  ...  23/09/2017  40.766115   
2  Real Bed            moderate          True  ...  14/09/2017  40.808110   
3  Real Bed            flexible          True  ...         NaN  37.772004   
4  Real Bed            moderate          True  ...  22/01/2017  38.925627   

    longitude                                      name     neighbourhood  \
0  -73.991617            Beautiful brownstone 1-bedroom  Brooklyn Heights   
1  -73.989040  Superb 3BR Apt Located Near Times Square    Hell's Kitchen   
2  -73.943756                          The Garden Oasis            Harlem   
3 -122.431619        Beautiful Flat in the Heart of SF!      Lower Haight   
4  -77.034596                Great studio in midtown DC  Columbia Heights   

  number_of_reviews review_scores_rating zipcode bedrooms  beds  
0                 2                100.0   11201      1.0   1.0  
1                 6                 93.0   10019      3.0   3.0  
2                10                 92.0   10027      1.0   3.0  
3                 0                  NaN   94117      2.0   2.0  
4                 4                 40.0   20009      0.0   1.0  

[5 rows x 28 columns]

In [41]:
bnb['log_price'].describe()

count    74111.000000
mean         4.782069
std          0.717394
min          0.000000
25%          4.317488
50%          4.709530
75%          5.220356
max          7.600402
Name: log_price, dtype: float64

In [42]:
#looking for appropriate columns
bnb['host_has_profile_pic'].value_counts()

t    73697
f      226
Name: host_has_profile_pic, dtype: int64

In [92]:
bnb=bnb[['log_price','accommodates','bathrooms','cleaning_fee','host_has_profile_pic','host_identity_verified','host_response_rate',
        'instant_bookable','number_of_reviews','review_scores_rating','bedrooms','beds']]

In [93]:
bnb.dropna(inplace=True)

In [94]:
bnb

log_price  accommodates  bathrooms  cleaning_fee host_has_profile_pic  \
1       5.129899             7        1.0          True                    t   
2       4.976734             5        1.0          True                    t   
4       4.744932             2        1.0          True                    t   
5       4.442651             2        1.0          True                    t   
6       4.418841             3        1.0          True                    t   
...          ...           ...        ...           ...                  ...   
74104   4.356709             2        1.0          True                    t   
74105   4.248495             2        1.0          True                    t   
74107   5.043425             4        2.0          True                    t   
74108   5.220356             5        1.0          True                    t   
74110   4.852030             4        1.0         False                    t   

      host_identity_verified host_response_rate instant_bookable  \
1                          f               100%                t   
2                          t               100%                t   
4                          t               100%                t   
5                          t               100%                t   
6                          f               100%                t   
...                      ...                ...              ...   
74104                      t               100%                f   
74105                      t                75%                f   
74107                      f               100%                f   
74108                      t               100%                t   
74110                      t               100%                f   

       number_of_reviews  review_scores_rating  bedrooms  beds  
1                      6                  93.0       3.0   3.0  
2                     10                  92.0       1.0   3.0  
4                      4                  40.0       0.0   1.0  
5                      3                 100.0       1.0   1.0  
6                     15                  97.0       1.0   1.0  
...                  ...                   ...       ...   ...  
74104                  6                 100.0       1.0   1.0  
74105                 36                  91.0       1.0   1.0  
74107                 16                  93.0       2.0   4.0  
74108                 43                  94.0       2.0   2.0  
74110                205                  96.0       1.0   2.0  

[47787 rows x 12 columns]

In [95]:
#Changing dtype
#Bool to Integer
bnb['cleaning_fee'] = bnb['cleaning_fee'].astype('int') 

d = {'t': True, 'f': False}
bnb['host_has_profile_pic']=bnb['host_has_profile_pic'].map(d).astype('bool').astype('int')
bnb['host_identity_verified']=bnb['host_identity_verified'].map(d).astype('bool').astype('int')
bnb['instant_bookable']=bnb['instant_bookable'].map(d).astype('bool').astype('int')
#
bnb['host_response_rate']=bnb['host_response_rate'].str.rstrip('%').astype('int')
bnb

log_price  accommodates  bathrooms  cleaning_fee  host_has_profile_pic  \
1       5.129899             7        1.0          True                     1   
2       4.976734             5        1.0          True                     1   
4       4.744932             2        1.0          True                     1   
5       4.442651             2        1.0          True                     1   
6       4.418841             3        1.0          True                     1   
...          ...           ...        ...           ...                   ...   
74104   4.356709             2        1.0          True                     1   
74105   4.248495             2        1.0          True                     1   
74107   5.043425             4        2.0          True                     1   
74108   5.220356             5        1.0          True                     1   
74110   4.852030             4        1.0         False                     1   

       host_identity_verified  host_response_rate  instant_bookable  \
1                           0                 100                 1   
2                           1                 100                 1   
4                           1                 100                 1   
5                           1                 100                 1   
6                           0                 100                 1   
...                       ...                 ...               ...   
74104                       1                 100                 0   
74105                       1                  75                 0   
74107                       0                 100                 0   
74108                       1                 100                 1   
74110                       1                 100                 0   

       number_of_reviews  review_scores_rating  bedrooms  beds  
1                      6                  93.0       3.0   3.0  
2                     10                  92.0       1.0   3.0  
4                      4                  40.0       0.0   1.0  
5                      3                 100.0       1.0   1.0  
6                     15                  97.0       1.0   1.0  
...                  ...                   ...       ...   ...  
74104                  6                 100.0       1.0   1.0  
74105                 36                  91.0       1.0   1.0  
74107                 16                  93.0       2.0   4.0  
74108                 43                  94.0       2.0   2.0  
74110                205                  96.0       1.0   2.0  

[47787 rows x 12 columns]

In [96]:
#Changing dtype
#Bool to Integer
bnb['cleaning_fee'] = bnb['cleaning_fee'].astype('int') 
bnb

log_price  accommodates  bathrooms  cleaning_fee  host_has_profile_pic  \
1       5.129899             7        1.0             1                     1   
2       4.976734             5        1.0             1                     1   
4       4.744932             2        1.0             1                     1   
5       4.442651             2        1.0             1                     1   
6       4.418841             3        1.0             1                     1   
...          ...           ...        ...           ...                   ...   
74104   4.356709             2        1.0             1                     1   
74105   4.248495             2        1.0             1                     1   
74107   5.043425             4        2.0             1                     1   
74108   5.220356             5        1.0             1                     1   
74110   4.852030             4        1.0             0                     1   

       host_identity_verified  host_response_rate  instant_bookable  \
1                           0                 100                 1   
2                           1                 100                 1   
4                           1                 100                 1   
5                           1                 100                 1   
6                           0                 100                 1   
...                       ...                 ...               ...   
74104                       1                 100                 0   
74105                       1                  75                 0   
74107                       0                 100                 0   
74108                       1                 100                 1   
74110                       1                 100                 0   

       number_of_reviews  review_scores_rating  bedrooms  beds  
1                      6                  93.0       3.0   3.0  
2                     10                  92.0       1.0   3.0  
4                      4                  40.0       0.0   1.0  
5                      3                 100.0       1.0   1.0  
6                     15                  97.0       1.0   1.0  
...                  ...                   ...       ...   ...  
74104                  6                 100.0       1.0   1.0  
74105                 36                  91.0       1.0   1.0  
74107                 16                  93.0       2.0   4.0  
74108                 43                  94.0       2.0   2.0  
74110                205                  96.0       1.0   2.0  

[47787 rows x 12 columns]

In [97]:
#making the Dv & Ivs into an array
y=bnb['log_price'].values
x=bnb[['accommodates','bathrooms','cleaning_fee','host_has_profile_pic','host_identity_verified','host_response_rate',
        'instant_bookable','number_of_reviews','review_scores_rating','bedrooms','beds']].values

In [98]:
print(x)
y=y.reshape(-1,1)
y

[[ 7.  1.  1. ... 93.  3.  3.]
 [ 5.  1.  1. ... 92.  1.  3.]
 [ 2.  1.  1. ... 40.  0.  1.]
 ...
 [ 4.  2.  1. ... 93.  2.  4.]
 [ 5.  1.  1. ... 94.  2.  2.]
 [ 4.  1.  0. ... 96.  1.  2.]]


array([[5.12989872],
       [4.97673374],
       [4.74493213],
       ...,
       [5.04342512],
       [5.22035583],
       [4.85203026]])

In [99]:
reg=LinearRegression()
reg.fit(x,y)

LinearRegression()

In [100]:
reg.score(x,y)

0.39022342326655846

In [101]:
y_pred=reg.predict(x)
y_pred

array([[5.42264702],
       [4.85240327],
       [3.9181226 ],
       ...,
       [4.87436297],
       [5.05204508],
       [4.71978415]])

In [102]:
np.sqrt(mean_squared_error(y,y_pred))

0.5276413053969746